config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  # mount ActionCable.server => '/cable'

  devise_for :users
  resources :properties do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :agreements, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      # patch 'complete', on: :member
      member do
        patch 'sign_owner'  # Owner signs the agreement
        patch 'send_to_tenant'  # Sends to tenant after owner signature
        patch 'complete'
        get 'sign_by_tenant'  # Route for tenant to access and sign the agreement
        patch 'update_by_tenant'  # Tenant signs the agreement
      end
    end
    resources :messages, only: [:index, :create]
    collection do
      get 'owner_dashboard'
    end
    member do
      get 'contact', to: 'properties#new_contact'
      post 'contact', to: 'properties#send_contact'
    end
  end

  patch '/update_language', to: 'users#update_language', as: 'update_language'

  # routes for blueprint supported APIs
  namespace :api do
    namespace :v1 do
      resources :properties, only: [:index, :show, :create, :update, :destroy] do
        # resources :comments, only: [:create, :edit, :update, :destroy]
        collection do
          get 'owner_dashboard', to: 'properties#owner_dashboard'
        end
        member do
          get 'contact', to: 'properties#new_contact'
          post 'contact', to: 'properties#send_contact'
        end
      end
    end
  end



  # resources :users
  # get 'home/index'
  root 'home#index'

  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/property.rb
class Property < ApplicationRecord

  searchkick

  # before_action :authenticate_user!, except: [:index, :show]

  validates :title, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, message: "must be a positive number" }
  validates :description, presence: true
  validates :address_line_1, presence: true
  validates :city, presence: true
  validates :postal_code, presence: true


  # If you want to customize the fields to be indexed, you can do it here
  def search_data
    # Rails.logger.info "Title: #{title}, City: #{city}, Postal Code: #{postal_code}, Address: #{address_line_1}"
    {
      title: title,
      description: description,
      price: price,
      status: status,
      address_line_1: address_line_1,
      address_line_2: address_line_2,
      city: city,
      postal_code: postal_code
    }
  end

  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :agreements
  has_many :messages
end

app/controllers/api/v1/properties_controller.rb
module Api
  module V1
    class PropertiesController < ApplicationController
      before_action :set_property, only: [:show, :update, :destroy]

      def new_contact
        @property = Property.find(params[:id])
        @user_email = current_user.email

        respond_to do |format|
          format.html
          format.json { render json: { property: PropertyBlueprint.render(@property), user_email: @user_email } }
        end
      end

      def send_contact
        @property = Property.find(params[:id])
        sender_email = params[:email]
        message = params[:message]

        # Call the mailer to send the email
        PropertyMailer.contact_owner(@property, message, sender_email).deliver_later

        respond_to do |format|
          format.html { redirect_to @property, notice: 'Your message has been sent to the property owner.' }
          format.json { render :show, status: :created, location: @property }
        end

        redirect_to @property, notice: 'Your message has been sent to the property owner.'
      end

      def owner_dashboard
        @properties = current_user.properties # Assuming current_user owns properties
        respond_to do |format|
          format.html
          format.json { render json: PropertyBlueprint.render(@properties) }
        end
      end

      def index
        if params[:query].present? && params[:query].strip != ''
          cache_key = "properties_search_#{params[:query].strip}" # Create a cache key based on the search query

          # loggers
          Rails.logger.debug("Cache Key: #{cache_key}")
          if Rails.cache.exist?(cache_key)
            Rails.logger.debug("Fetching from cache for key: #{cache_key}")
          else
            Rails.logger.debug("Cache miss for key: #{cache_key}")
          end

          @properties = Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
            properties = Property.search(params[:query], fields: [:description, :title, :city, :postal_code, :address_line_1, :address_line_2])
            Rails.logger.debug("Query executed, properties count: #{properties.count}")
            properties
          end
        else
          cache_key = 'properties_all' # Cache key for all properties without a search query
          @properties = Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
            Property.all
          end
        end

        respond_to do |format|
          format.json { render json: PropertyBlueprint.render(@properties), status: :ok } # JSON response for API
          format.html # regular HTML response
        end
      end

      def new
        # @property = Property.new
        @property = current_user.properties.build
      end

      def edit
      end

      def show
        cache_key = "property_#{params[:id]}"
        @property = Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
          Property.find(params[:id])
        end

        if @property
          respond_to do |format|
            format.json { render json: PropertyBlueprint.render(@property), status: :ok } # JSON response for API
            format.html # regular HTML response
          end
        else
          respond_to do |format|
            format.json { render json: { error: "Property not found" }, status: :not_found } # Error response for API
            format.html { redirect_to properties_path, alert: "Property not found" } # Redirect for HTML
          end
        end
      end

      def create
        # @property = Property.new(property_params)
        @property = current_user.properties.build(property_params)
        @property.user = current_user # Assuming you have a `current_user` method for authentication

        if @property.save
          Rails.cache.delete('properties_all') # Invalidate the cache for the index view
          respond_to do |format|
            format.html { redirect_to properties_path, notice: 'Property posted successfully!' }
            format.json { render json: PropertyBlueprint.render(@property), status: :created } # Return the created property in JSON format
          end
        else
          respond_to do |format|
            format.html { render :new }
            format.json { render json: { errors: @property.errors.full_messages }, status: :unprocessable_entity } # Return validation errors
          end
        end
      end

      def update

        # Handle removing selected images
        if params[:property][:remove_images].present?
          params[:property][:remove_images].each do |image_id|
            image = @property.images.find(image_id)
            image.purge # This deletes the image from ActiveStorage
          end
        end

        # If new images are provided, merge them with existing images
        if params[:property][:images].present?
          @property.images.attach(params[:property][:images])
        end

        if @property.update(property_params.except(:images))
          Rails.cache.delete("property_#{@property.id}") # Invalidate the cache for the updated property
          Rails.cache.delete('properties_all') # Invalidate the index cache
          respond_to do |format|
            format.html { redirect_to @property }
            format.json { render json: PropertyBlueprint.render(@property), status: :ok } # Return the updated property
          end
        else
          respond_to do |format|
            format.html { render 'edit' }
            format.json { render json: { errors: @property.errors.full_messages }, status: :unprocessable_entity }
          end
        end
      end

      def destroy
        @property.destroy
        Rails.cache.delete("property_#{@property.id}") # Remove the specific property's cache
        Rails.cache.delete('properties_all') # Invalidate the cache for the index view
        respond_to do |format|
          format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private

      def property_params
        params.require(:property).permit(:user_id, :price, :description, :status, { images: [] }, :latitude, :longitude, :address_line_1, :address_line_2, :city, :postal_code, :title)
      end

      def set_property
        @property = Property.find_by(id: params[:id])
        unless @property
          render json: { error: "Property not found" }, status: :not_found
        end
      end


      def authorize_owner!
        unless @property.user == current_user
          redirect_to @property, alert: 'You are not authorized to perform this action.'
        end
      end

    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  # before_action :authenticate_user!, except: [:index, :show]
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authorize_owner!, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:owner_dashboard]

  def new_contact
    @property = Property.find(params[:id])
    @user_email = current_user.email
  end

  def send_contact
    @property = Property.find(params[:id])
    sender_email = params[:email]
    message = params[:message]

    # Call the mailer to send the email
    PropertyMailer.contact_owner(@property, message, sender_email).deliver_later

    redirect_to @property, notice: 'Your message has been sent to the property owner.'
  end

  def owner_dashboard
    @properties = Property.includes(:user, images_attachments: :blob).where(user_id: current_user.id)
  end

  def index
    if params[:query].present? && params[:query].strip != ''
      cache_key = "properties_search_#{params[:query].strip}_user_#{current_user&.id || 'guest'}" # Use 'guest' if no user is logged in

      # Loggers
      Rails.logger.debug("Cache Key: #{cache_key}")
      if Rails.cache.exist?(cache_key)
        Rails.logger.debug("Fetching from cache for key: #{cache_key}")
      else
        Rails.logger.debug("Cache miss for key: #{cache_key}")
      end

      @properties = Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
        properties = Property.search(params[:query], fields: [:description, :title, :city, :postal_code, :address_line_1, :address_line_2]).includes(:user, images_attachments: :blob)

        # Ensure @properties is an ActiveRecord relation to allow further chaining
        if properties.is_a?(ActiveRecord::Relation)
          properties = properties.where.not(user_id: current_user.id) if current_user
        else
          # Convert the search result to an array and apply filtering
          properties = properties.to_a.reject { |property| property.user_id == current_user.id } if current_user
        end

        Rails.logger.debug("Query executed, properties count: #{properties.count}")
        properties
      end
    else
      cache_key = "properties_all_user_#{current_user&.id || 'guest'}" # Use 'guest' for no user logged in
      @properties = Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
        properties = Property.includes(:user, images_attachments: :blob).all
        properties = properties.where.not(user_id: current_user.id) if current_user
        properties
      end
    end

    if @properties.is_a?(ActiveRecord::Relation)
      @properties = @properties.order(created_at: :desc)
    else
      @properties = @properties.sort_by(&:created_at).reverse # For array of properties
    end

    # Add pagination after fetching properties
    if @properties.is_a?(Array)
      @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(3)
    else
      @properties = @properties.page(params[:page]).per(3)
    end
  end


  def new
    # @property = Property.new
    @property = current_user.properties.build
  end

  def edit
  end


  def show
    cache_key = "property_#{params[:id]}"
    @property = Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
      Property.includes(
        images_attachments: :blob
      ).find(params[:id])
    end
  end


  def create
    @property = current_user.properties.build(property_params)
    @property.user = current_user

    if @property.save
      Rails.cache.delete("property/#{@property.id}/title")
      Rails.cache.delete("property/#{@property.id}/city")
      Rails.cache.delete("property/#{@property.id}/description")
      Rails.cache.delete("property/#{@property.id}/address_line_1")
      Rails.cache.delete("property/#{@property.id}/address_line_2")
      Rails.cache.delete("properties_search_#{@property.title}_user_guest")
      Rails.cache.delete("properties_search_#{@property.city}_user_guest")
      Rails.cache.delete("properties_search_#{@property.description}_user_guest")
      Rails.cache.delete("properties_search_#{@property.address_line_1}_user_guest")
      Rails.cache.delete("properties_search_#{@property.address_line_2}_user_guest")
      Rails.cache.delete('properties_all')
      redirect_to owner_dashboard_properties_path, notice: 'Property posted successfully!'
    else
      puts @property.errors.full_messages
      render :new
    end
  end

  def update

    # Handle removing selected images
    if params[:property][:remove_images].present?
      params[:property][:remove_images].each do |image_id|
        image = @property.images.find(image_id)
        image.purge # This deletes the image from ActiveStorage
      end
    end

    # If new images are provided, merge them with existing images
    if params[:property][:images].present?
      @property.images.attach(params[:property][:images])
    end

    if @property.update(property_params.except(:images))
      Rails.cache.delete("property_#{@property.id}") # Invalidate the cache for the updated property
      Rails.cache.delete('properties_all') # Invalidate the index cache
      redirect_to @property
    else
      render 'edit'
    end
  end

  def destroy
    @property.destroy
    Rails.cache.delete("property_#{@property.id}") # Remove the specific property's cache
    Rails.cache.delete('properties_all') # Invalidate the cache for the index view
    redirect_to owner_dashboard_properties_path, notice: 'Property was successfully destroyed.'
  end

  def show_agreement
    @property = Property.find(params[:id])

    # Find the current year's agreement for the property
    @current_year_agreement = @property.agreements.find_by("extract(year from start_date) = ?", Date.current.year)
  end


  private

  def property_params
    params.require(:property).permit(:user_id, :price, :description, :status, {images: []}, :latitude, :longitude, :address_line_1, :address_line_2, :city, :postal_code, :title)
  end

  def set_property
    @property = Property.find(params[:id])
  end

  def authorize_owner!
    unless @property.user == current_user
      redirect_to @property, alert: 'You are not authorized to perform this action.'
    end
  end


end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: @property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :address_line_1 %>
    <%= form.text_field :address_line_1, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :address_line_2 %>
    <%= form.text_field :address_line_2, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :postal_code %>
    <%= form.number_field :postal_code, class:"form-control" %>
  </div>

<!--  <div class="field form-group">-->
    <%#= form.label :status %>
    <%#= form.text_field :status, class:"form-control" %>
<!--  </div>-->

  <% if @property.images.attached? %>
    <div class="form-group">
      <label>Existing Images</label>
      <div class="row">
        <% @property.images.each do |image| %>
          <div class="col-md-3">
            <!-- Display the image -->
            <%= link_to image_tag(image, size: "200x200"), url_for(image), target: "_blank" %>
            <!-- Delete Checkbox -->
            <div class="form-check">
              <%= check_box_tag "property[remove_images][]", image.id, false, class: "form-check-input" %>
              <%= label_tag "property[remove_images][]", "Delete", class: "form-check-label" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>


  <div class="field form-group">
    <%= form.label :images, "Upload Images" %>
    <%= form.file_field :images, multiple: true, class:"form-control" %>
  </div>

<!--  <div class="field form-group">-->
    <%#= form.label :latitude %>
    <%#= form.text_field :latitude, class:"form-control" %>
<!--  </div>-->

<!--  <div class="field form-group">-->
    <%#= form.label :longitude %>
    <%#= form.text_field :longitude, class:"form-control" %>
<!--  </div>-->

  <br>

  <%= form.submit class:'btn btn-primary' %>
<% end %>

app/views/properties/destroy.html.erb
<h1>Property#destroy</h1>
<p>Find me in app/views/property/destroy.html.erb</p>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<!--<%#= link_to 'Show', @property %> |-->
<br>
<%= link_to 'Back', properties_path, class:'btn btn-secondary' %>

app/views/properties/index.html.erb
<%= form_with url: properties_path, method: :get, local: true, class: "form-inline my-2 my-lg-0" do %>
  <%= text_field_tag :query, params[:query], placeholder: t('home.search'), class: "form-control mr-sm-2", style: "width: 400px;" %>
  <%= submit_tag t('action.search'), class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>

<br>
<br>

<h1>Listed Properties</h1>

<% if @properties.any? %>
  <% @properties.each do |property| %>
    <div>
      <h2><%= link_to property.title, property_path(property, source: 'tenant') %></h2>
      <p>Rent: <%= property.price %> | City: <%= property.city %></p>
      <% if property.images.present? %>
        <% property.images.first(3).each do |image| %>
          <%= link_to image_tag(image, size: "200x200"), url_for(image), target: "_blank" %>
        <% end %>
      <% end %>
    </div>
    <br>
  <% end %>

  <!-- Pagination -->
  <div class="pagination">
    <%= paginate @properties %>
  </div>

<% else %>
  <p>No properties found.</p>
<% end %>

app/views/properties/new.html.erb
<h1>Post a Property</h1>

<br/>
<%= render 'form', property: @property %>

<br>
<%= link_to 'Back', properties_path, class:'btn btn-secondary' %>

app/views/properties/new_contact.html.erb
<h1>Contact Property Owner</h1>

<%= form_with url: contact_property_path(@property), local: true do %>
  <div class="form-group">
    <%= label_tag :email, "Your Email" %>
    <%= text_field_tag :email, @user_email, class: 'form-control', readonly: true %>
  </div>

  <div class="form-group">
    <%= label_tag :message, "Your Message" %>
    <%= text_area_tag :message, nil, class: 'form-control' %>
  </div>

  <%= submit_tag 'Send Message', class: 'btn btn-primary' %>
<% end %>

app/views/properties/owner_dashboard.html.erb
<h1><%= t('custom.owner_dashboard') %></h1>
<br>
<%= link_to t('custom.post_new_property'), new_property_path, class: 'btn btn-success' %>

<%#= link_to 'Rental Agreement', new_agreement_path, class: 'btn btn-success' %>

<br><br>
<h2><%= t('custom.listed_properties') %></h2>

<% if @properties.any? %>
  <% @properties.each do |property| %>
    <div>
      <h2><%= link_to property.title, property_path(property) %></h2>
      <p><%= t('custom.rent') %>: <%= property.price %> | <%= t('custom.city') %>: <%= property.city %></p>
      <% if property.images.present? %>
        <% property.images.first(3).each do |image| %>
          <%= link_to image_tag(image, size: "200x200"), url_for(image), target: "_blank" %>
        <% end %>
      <% end %>
    </div>
    <br>
    
    <br><br>
  <% end %>
<% else %>
  <p>No properties found. You can <%= link_to 'post a new property', new_property_path %> now.</p>
<% end %>

app/views/properties/show.html.erb
<h1><%= @property.title %></h1>

<div class="property-details">
  <p><strong>Rent:</strong> <%= @property.price %></p>
  <p><strong>Description:</strong> <%= @property.description %></p>
  <p><strong>City</strong>: <%= @property.city %></p>
  <p><strong>Status:</strong> <%= @property.status %></p>
  <p><strong>Location:</strong> Latitude: <%= @property.latitude %>, Longitude: <%= @property.longitude %></p>

  <p><strong>Address:</strong>
    <%= @property.address_line_1 %>,
    <%= @property.address_line_2 %>,
    <%= @property.city %>,
    <%= @property.postal_code %>
  </p>

  <% if @property.images.present? %>
    <% @property.images.each do |image| %>
      <%= link_to image_tag(image, size: "200x200"), url_for(image), target: "_blank" %>
    <% end %>
  <% end %>
</div>


<br>

<% if @property.user == current_user %>
  <%= link_to t('action.edit'), edit_property_path(@property), class:"btn btn-secondary" %>
  <%= link_to t('action.delete'), @property, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<% end %>


<% if params[:source] == 'tenant' %>
  <%= link_to 'Back to Properties', properties_path, class: "btn btn-secondary" %>
<% else %>
  <%= link_to 'Back to My Properties', owner_dashboard_properties_path, class: "btn btn-secondary" %>
<% end %>

<% if user_signed_in? && current_user == @property.user%>
  <%= link_to 'Rental Agreement', property_agreements_path(@property), class: "btn btn-secondary" %>
<% end %>

<hr>

<!-- Comments Section -->
<h3>Comments</h3>

<!-- Comment Form -->
<% if user_signed_in? %>
  <% if current_user != @property.user %>
    <%= link_to 'Contact Owner', contact_property_path(@property), class: "btn btn-primary" %>
  <% end %>

<!--  <div id="property" data-id="<%#= @property.id %>">-->
<!--    <h3>Chat</h3>-->
<!--    <div id="messages"></div>-->
<!--    <form id="message-form">-->
<!--      <input type="hidden" id="receiver-id" value="<%#= @property.user_id %>"> -->
<!--      <label for="message-content"></label>-->
<!--      <input type="text" id="message-content" placeholder="Type a message..." required>-->
<!--      <button type="submit">Send</button>-->
<!--    </form>-->
<!--  </div>-->

  <%#= javascript_pack_tag 'chat' %>

  <%= render 'comments/form', property: @property, comment: Comment.new %>
<% else %>
  <p>Please login to post a comment!</p>
<% end %>

<% @property.comments.each do |comment| %>
  <div class="comment">
    <strong><%= comment.user.email %>:</strong>
    <p><%= comment.body %></p>

    <% if comment.user == current_user %>
      <%= link_to 'Edit', edit_property_comment_path(@property, comment), class: 'btn btn-sm btn-warning' %>
      <%= link_to 'Delete', property_comment_path(@property, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
    <% end %>
  </div>
<% end %>