config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  # mount ActionCable.server => '/cable'

  devise_for :users
  resources :properties do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :agreements, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      # patch 'complete', on: :member
      member do
        patch 'sign_owner'  # Owner signs the agreement
        patch 'send_to_tenant'  # Sends to tenant after owner signature
        patch 'complete'
        get 'sign_by_tenant'  # Route for tenant to access and sign the agreement
        patch 'update_by_tenant'  # Tenant signs the agreement
      end
    end
    resources :messages, only: [:index, :create]
    collection do
      get 'owner_dashboard'
    end
    member do
      get 'contact', to: 'properties#new_contact'
      post 'contact', to: 'properties#send_contact'
    end
  end

  patch '/update_language', to: 'users#update_language', as: 'update_language'

  # routes for blueprint supported APIs
  namespace :api do
    namespace :v1 do
      resources :properties, only: [:index, :show, :create, :update, :destroy] do
        # resources :comments, only: [:create, :edit, :update, :destroy]
        collection do
          get 'owner_dashboard', to: 'properties#owner_dashboard'
        end
        member do
          get 'contact', to: 'properties#new_contact'
          post 'contact', to: 'properties#send_contact'
        end
      end
    end
  end



  # resources :users
  # get 'home/index'
  root 'home#index'

  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @properties = Property.all
  end

  def about

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'NestFinder', root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to t('menu.about'), home_about_path, class:"nav-link" %>
      </li>

      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to t('menu.edit_profile'), edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to t('menu.property_owners'), owner_dashboard_properties_path, class:"nav-link" %>
        </li>

        <%# if current_user.admin? %>
<!--          <li class="nav-item">-->
            <%#= link_to 'Admin Dashboard', admin_dashboard_path %>
<!--          </li>-->
        <%# end %>


        <li class="nav-item">
          <%= link_to t('menu.sign_out'), destroy_user_session_path, method: :delete, class:"nav-link", data: { turbo_method: :delete } %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>

    <%= form_with url: update_language_path, method: :patch, remote: true, id: "language_form" do %>
      <%= select_tag 'language', options_for_select([['English', 'en'], ['French', 'fr']], I18n.locale), onchange: "this.form.submit()" %>
    <% end %>
  </div>
</nav>

app/views/home/about.html.erb
<h1><%= t('menu.about') %></h1>

<p1>

  At NestFinder, we're on a mission to revolutionize the way people buy, sell, and rent properties. Tired of unnecessary middlemen and hefty brokerage fees, we set out to create a platform that puts the power back into your hands. Our app connects homeowners, buyers, and renters directly, making real estate transactions simpler, more transparent, and hassle-free.
  <br>
  <br>

  With a focus on ease of use and security, NestFinder provides a comprehensive set of tools to list properties, find your dream home, and close deals — all without the need for a broker. Whether you're searching for a cozy apartment or putting your property up for sale, we've got you covered.
  <br><br>

  We believe in transparency, fairness, and efficiency. That's why our app features powerful search filters, real-time updates, and secure communication channels, ensuring that you have everything you need to make informed decisions.
  <br><br>

  Join us on our journey to make property transactions smoother, faster, and broker-free!
  <br><br>

  <h3><%= t('custom.contact') %></h3>
  <br>
  <p1>In case you have any questions, suggestions or if you just want to have a general talk with us. You can reach out to us by any of the below means:</p1>
  <br><br>
  <p1>hello@nestfinder.com</p1>
  <br>
  <p1>123456789</p1>
</p1>

app/views/home/index.html.erb
<h1>NestFinder</h1>
<p><%= t('home.tagline') %> </p>

<div>
  <%= form_with url: properties_path, method: :get, local: true, class: "form-inline my-2 my-lg-0" do %>
    <%= text_field_tag :query, params[:query], placeholder: t('home.search'), class: "form-control mr-sm-2", style: "width: 400px;" %>
    <%= submit_tag t('action.search'), class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
</div>